"""empty message

Revision ID: ba62e08967fa
Revises: 
Create Date: 2018-02-06 22:51:24.624502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba62e08967fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_field_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('risk_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('risk_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=150), nullable=True),
    sa.Column('risk_field_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_field_type_id'], ['risk_field_type.id'], ),
    sa.ForeignKeyConstraint(['risk_type_id'], ['risk_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_field_enum_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_field_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['risk_field_type_id'], ['risk_field_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_field_enum_value')
    op.drop_table('risk_field')
    op.drop_table('risk_type')
    op.drop_table('risk_field_type')
    # ### end Alembic commands ###
